import 'models/authentication_one_model.dart';import 'package:ecomapp/core/app_export.dart';import 'package:ecomapp/widgets/custom_elevated_button.dart';import 'package:ecomapp/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'provider/authentication_one_provider.dart';class AuthenticationOneScreen extends StatefulWidget {const AuthenticationOneScreen({Key? key}) : super(key: key);

@override AuthenticationOneScreenState createState() =>  AuthenticationOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => AuthenticationOneProvider(), child: AuthenticationOneScreen()); } 
 }
class AuthenticationOneScreenState extends State<AuthenticationOneScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(width: double.maxFinite, padding: EdgeInsets.all(31.h), decoration: AppDecoration.fillPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 56.v), _buildFruitBasket(context), SizedBox(height: 4.v), _buildOrderDetails(context)])), SizedBox(height: 58.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_what_is_your_firstname".tr, style: theme.textTheme.titleLarge))), SizedBox(height: 13.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Selector<AuthenticationOneProvider, TextEditingController?>(selector: (context, provider) => provider.firstNameController, builder: (context, firstNameController, child) {return CustomTextFormField(controller: firstNameController, hintText: "lbl_tony".tr, textInputAction: TextInputAction.done);})), SizedBox(height: 42.v), CustomElevatedButton(height: 56.v, text: "lbl_start_ordering".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700, onPressed: () {onTapStartOrdering(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildFruitBasket(BuildContext context) { return SizedBox(height: 284.v, width: 301.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFruitDrops2RemovebgPreview, height: 37.v, width: 50.h, alignment: Alignment.topRight), CustomImageView(imagePath: ImageConstant.imgKisspngFruitB, height: 281.v, width: 301.h, alignment: Alignment.center)])); } 
/// Section Widget
Widget _buildOrderDetails(BuildContext context) { return Container(height: 18.v, width: 301.h, margin: EdgeInsets.only(left: 6.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 12.v, width: 301.h, decoration: BoxDecoration(color: appTheme.yellow900, borderRadius: BorderRadius.circular(150.h)))), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 19.h, right: 9.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Container(height: 9.v, width: 23.h, margin: EdgeInsets.only(top: 7.v), decoration: BoxDecoration(color: appTheme.yellow900, borderRadius: BorderRadius.circular(11.h))), Spacer(), Container(height: 9.v, width: 23.h, margin: EdgeInsets.only(top: 9.v), decoration: BoxDecoration(color: appTheme.yellow900, borderRadius: BorderRadius.circular(11.h))), Container(height: 9.v, width: 23.h, margin: EdgeInsets.only(left: 9.h, bottom: 9.v), decoration: BoxDecoration(color: appTheme.yellow900, borderRadius: BorderRadius.circular(11.h)))])))])); } 
/// Navigates to the authenticationFourScreen when the action is triggered.
onTapStartOrdering(BuildContext context) { NavigatorService.pushNamed(AppRoutes.authenticationFourScreen, ); } 
 }
